#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Mac Swiss Artmy Knife
# https://github.com/rgcr/m-cli
#
export PATH=$PATH:/usr/local/m-cli

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
  ${HOME}/bin
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"


# golang
export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin


# java
case `uname` in
  Darwin)
    export JAVA_HOME=$(/usr/libexec/java_home)
    ;;
  Linux)
    # do nothing just now
    ;;
esac


# ruby
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting


# general
export PATH="$PATH:$HOME/bin/"


# node
export PATH="$PATH:$HOME/apps/node/bin/"


# docker
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_CERT_PATH=~/.docker/machine/machines/default
export DOCKER_MACHINE_NAME=default


# erlang
export PATH="$PATH:$HOME/apps/erlang/lib/erl_interface-3.8/bin/"


# maven
export MAVEN_OPTS="-Xms512m -Xmx1024m -XX:PermSize=256m"
