#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -s "/Users/dboroujerdi/.dnx/dnvm/dnvm.sh" ] && . "/Users/dboroujerdi/.dnx/dnvm/dnvm.sh" # Load dnvm
