#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -s "/Users/dboroujerdi/.dnx/dnvm/dnvm.sh" ] && . "/Users/dboroujerdi/.dnx/dnvm/dnvm.sh" # Load dnvm


# aliases

## Aliases
alias l='ls -CF'
alias ls='ls -G'
alias ll='ls -alF'
alias lx='ls -lXB'         # sort by extension
alias lk='ls -lSr'         # sort by size
alias la='ls -Al'          # show hidden files
alias lr='ls -lR'          # recursive ls
alias lt='ls -ltr'         # sort by date
alias lsize='ls --sort=size -lhr' # list by size

## Tree aliases
alias tl='tree -L 1'
alias tree2='tree -L 2'
alias tree3='tree -L 3'

alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p -v'
alias df='df -h'
alias du='du -h -c'
alias reload='source ~/.bashrc'
alias biggest='BLOCKSIZE=1048576; du -x | sort -nr | head -10'

# git
alias gs='git status'
alias gl='git lg'
alias gc='git commit'
alias gd='git diff'
alias gt='git tree'

# emacs
alias e='emacsclient -nw -c'
alias ed='emacs --daemon'

# Maven
alias mci='mvn clean install'
alias mver='mvn -version'
alias mc='mvn clean'

alias rabbit_delete_queues='for queue in `rabbitmqadmin -f bash list queues name`; do rabbitmqadmin delete queue name="$queue"; done'

# Docker
alias rabbit_on='docker run -d --name rabbit -p 5672:5672 -p 15672:15672 rabbitmq:3-management'
alias kafka_on="docker run -d --name kafka -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST='10.1.74.46' --env ADVERTISED_PORT=9092 spotify/kafka"

# Erlang
alias emk_init='wget https://raw.githubusercontent.com/ninenines/erlang.mk/master/erlang.mk && make -f erlang.mk bootstrap'

# Functions
kafka_local_clean() {
  sudo rm -rf /tmp/zookeeper
  sudo rm -rf /tmp/kafka-logs
}

kafka_local_on() {
  # start zookeeper
  ~/apps/kafka/bin/zookeeper-server-start.sh config/zookeeper.properties &
  # start kafka
  ~/apps/kafka/bin/kafka-server-start.sh config/server.properties &
}

kafka_local_off() {
  # stop kafka
  ~/apps/kafka/bin/kafka-server-stop.sh
  # stop zookeeper
  ~/bin/kafka/bin/zookeeper-server-start.sh config/zookeeper.properties
}

kafka_list_topics() {
  ~/apps/kafka/bin/kafka-topics.sh --list --zookeeper localhost:2181
}

kafka_delete_topic() {
  ~/apps/kafka/bin/kafka-topics.sh --delete --topic $1 --zookeeper localhost:2181
}

kafka_consume_topic() {
  ~/apps/kafka/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic $1 --from-beginning
}

kafka_produce_topic() {
  ~/apps/kafka/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic $1
}

kafka_create_topic() {
  ~/apps/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic $1
}
